### ISSUE TITLE
"Invalid Form Key. Please refresh the page."

### ISSUE THREAD

**Issue by softwareofsweden** [DIBS-Payment-Services/magento2-flexwin#42]
I think the controllers must implement CsrfAwareActionInterface in order to work in Magento 2.3.x.

I did a test by implementing it on the base controller (Dibs\Flexwin\Controller\Index) and that helped. The error was gone and it was possible to place an order.

However, it won't be compatible with pre 2.3 versions so might be a problem...

**Comment by maxwhite** [comment]
it was fixed: https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/commit/aef5dc9ad60bd29804b4d335a28239f64b0ceac7

**Comment by softwareofsweden** [comment]
Ok, but I think it will have to handle other actions beside "callback" aswell... E.g. if you cancel an order you will get the error.

**Comment by maxwhite** [comment]
we will check it

**Comment by marinagociu** [comment]
This is still an issue with the latest version of Magento. It was partially fixed with the plugin mentioned in the above comments but it's still an issue for the other controllers that are accepting POST requests, like `Dibs\Flexwin\Controller\Index\Accept` and `Dibs\Flexwin\Controller\Index\Cancel`. The controllers need to either implement the Magento interface or they need to be included in the validation skip in the plugin.

**Comment by softwareofsweden** [comment]
In CsrfValidatorSkip you should also check for 'accept' action. Otherwise you will get an Invalid Form Key instead of showing the order confirmation page with reciept.

**Comment by maxwhite** [comment]
@softwareofsweden , 
https://github.com/DIBS-Payment-Services/magento2-flexwin/issues/42#issuecomment-689548071
